server:
  port: 8080
spring:
  application:
  name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: http://localhost:8082   # Địa chỉ Order Service
          predicates:
            - Path=/api/orders/**
        - id: product-service
          uri: http://localhost:8083   # Địa chỉ Product Service
          predicates:
            - Path=/api/products/**
        - id: payment-service
          uri: http://localhost:8084   # Địa chỉ Payment Service
          predicates:
            - Path=/api/payments/**

#    default-filters:
#      - AddRequestHeader=X-Gateway-Source, Spring-Gateway
