server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update



